#!/bin/sh
#
# SETTING KAKA'AKOS CHIRP
#
# Set AD9854 clock remap to 25 MHz
export PATH=$PATH:/usr/local/bin

set.ddsC 	CR	004C0041
set.ddsC 	FTW1 	1AAAAAAAAAAA

# Program AD9512 secondary clock to choose 25 MHz from the AD9854 remap
set.clkdB	CSPD	02
set.clkdB	UPDATE	01


# Program the chirp using Kaka'ako parameters
set.site 2 ddsA_upd_clk_fpga 1
set.ddsA	CR	004F0061
set.ddsA	FTW1	172B020C49BA
set.ddsA	DFR	0000000021D1
set.ddsA	UCR	01F01FD0
set.ddsA	RRCR	000001
set.ddsA	IPDMR	0FFF
set.ddsA	QPDMR	0FFF
set.ddsA	CR	004C8761


# Set the trigger
set.site 2 ddsA_upd_clk_fpga 0
# pgm .. not needed
#echo b > /dev/acq400.0.knobs/fpctl_sync


# lera_acq_setup
# we assume a 25MHz from ddsC
# trigger from site 3 ddsA
set.site 1 trg 1,3,1
set.site 1 clk 1,3,1
set.site 1 hi_res_mode 1
# 25 MHz/4 = 6.25MHz / 512 = SR 12207
set.site 1 CLKDIV 4



